"""
Django settings for robotat_web project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# ======================================================================================
# Archivo: settings.py
# Ubicación: backend/robotat_web/
#
# Descripción general:
# --------------------------------------------------------------------------------------
# Este archivo define la configuración principal del proyecto Django "robotat_web".
# Contiene todos los parámetros que controlan el comportamiento del sistema,
# incluyendo seguridad, aplicaciones instaladas, base de datos, rutas, autenticación,
# JWT, CORS y configuración para comunicación en tiempo real con Channels.
#
# Autora: Sara Hernández 
# Colaborador: ChatGPT 
# ======================================================================================


# =========================
# Importaciones de utilería
# =========================
from pathlib import Path                               # Módulo para construir rutas independientes del sistema operativo
from datetime import timedelta                         # Clase para definir intervalos de tiempo (usada en JWT)


# =========================
# Rutas base del proyecto
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent       # Ruta raíz del proyecto, donde se encuentra manage.py


# =============================================
# Seguridad básica y modo debug (solo desarrollo)
# =============================================
SECRET_KEY = 'django-insecure-5fimo2acvwjh&cg2890#@xf$&44tg(cnpoo-zer31s8#mw#aw-'  # Clave secreta (solo para entorno local)
DEBUG = True                                            # Activa el modo de depuración, mostrar errores detallados
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']              # Lista de hosts autorizados para servir la aplicación


# =================
# Apps instaladas
# =================
INSTALLED_APPS = [
    # Núcleo de Django
    'django.contrib.admin',                             # Aplicación del panel administrativo
    'django.contrib.auth',                              # Sistema de autenticación y permisos
    'django.contrib.contenttypes',                      # Mapeo de modelos y tipos de contenido
    'django.contrib.sessions',                          # Manejo de sesiones (útil para admin)
    'django.contrib.messages',                          # Framework de mensajes
    'django.contrib.staticfiles',                       # Manejo de archivos estáticos (CSS, JS, etc.)

    # App principal del sistema Robotat
    'interfaz',                                         # Contiene los modelos, vistas y serializadores de usuario

    # CORS Headers (permite comunicación con frontend en otro puerto)
    'corsheaders',                                      # Permite solicitudes cruzadas de dominio (CORS)

    # Django REST Framework y JWT
    'rest_framework',                                   # Framework para construcción de APIs
    'rest_framework_simplejwt',                         # Autenticación basada en tokens JWT

    # Blacklist de tokens (permite invalidar refresh tokens antiguos)
    'rest_framework_simplejwt.token_blacklist',

    # App de cámaras (streaming y control PTZ)
    'camaras',

    # Channels y MQTT (comunicación en tiempo real)
    'channels',                                         # Implementación de WebSockets
    'mqtt_bridge',                                      # Manejo de cliente MQTT y WebSockets
]


# =================
# Middleware
# =================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',    # Añade cabeceras de seguridad básicas

    # CORS debe ejecutarse temprano para modificar cabeceras antes de procesar la solicitud
    'corsheaders.middleware.CorsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',  # Gestiona sesiones en el admin
    'django.middleware.common.CommonMiddleware',        # Funcionalidades comunes (cache, encabezados, etc.)
    'django.middleware.csrf.CsrfViewMiddleware',        # Protección CSRF (no aplica para JWT)
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Inyecta request.user según autenticación
    'django.contrib.messages.middleware.MessageMiddleware',     # Permite enviar mensajes al usuario
    'django.middleware.clickjacking.XFrameOptionsMiddleware',   # Previene ataques de clickjacking
]


# =================
# Enrutamiento raíz
# =================
ROOT_URLCONF = 'robotat_web.urls'                       # Archivo donde se definen las rutas globales del proyecto


# =================
# Templates
# =================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Motor de plantillas
        'DIRS': [],                                        # Directorios adicionales de templates (vacío por ahora)
        'APP_DIRS': True,                                  # Busca templates dentro de cada app
        'OPTIONS': {
            'context_processors': [                        # Contexto común disponible en todos los templates
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# =================
# WSGI (despliegue clásico)
# =================
WSGI_APPLICATION = 'robotat_web.wsgi.application'        # Punto de entrada WSGI para servidores tradicionales


# =================
# ASGI (para WebSockets y tiempo real)
# =================
ASGI_APPLICATION = 'robotat_web.asgi.application'        # Punto de entrada ASGI usado por Django Channels


# =================
# Base de datos
# =================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',          # Usa SQLite en desarrollo (archivo físico local)
        'NAME': BASE_DIR / 'db.sqlite3',                 # Ruta del archivo de base de datos
    }
}


# ===================================
# Validadores de contraseñas (Django)
# ===================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},  # Evita contraseñas similares al usuario
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},            # Longitud mínima
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},           # Evita contraseñas comunes
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},          # Evita contraseñas solo numéricas
]


# =================
# Internacionalización
# =================
LANGUAGE_CODE = 'es'                                  # Idioma por defecto (Español)
TIME_ZONE = 'America/Guatemala'                       # Zona horaria local
USE_I18N = True                                       # Activa traducción de textos
USE_TZ = True                                         # Guarda tiempos en UTC y los convierte localmente


# =================
# Archivos estáticos
# =================
STATIC_URL = 'static/'                                # Prefijo de las URLs de archivos estáticos
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Campo autoincremental por defecto para los modelos


# ==============================
# Modelo de usuario personalizado
# ==============================
AUTH_USER_MODEL = 'interfaz.UsuarioPersonalizado'     # Define el modelo de usuario usado por el sistema


# =================
# CORS (frontend)
# =================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",                          # URL del frontend en modo desarrollo
    "http://127.0.0.1:5173",
]


# =================
# CSRF (seguridad de formularios)
# =================
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",                          # Permite confianza en solicitudes desde el frontend local
    "http://127.0.0.1:5173",
]


# =================
# Django REST Framework (DRF)
# =================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Autenticación principal por JWT
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',          # Permisos abiertos por defecto (restringidos por vista)
    ],
}


# =================
# Simple JWT (configuración de tokens)
# =================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),    # Duración del access token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),       # Duración del refresh token
    'ROTATE_REFRESH_TOKENS': True,                     # Genera un refresh token nuevo al refrescar
    'BLACKLIST_AFTER_ROTATION': True,                  # Invalida el refresh token anterior
    'AUTH_HEADER_TYPES': ('Bearer',),                  # Prefijo usado en el encabezado Authorization
}


# ===========================================================
# Configuración de correo (solo entorno de desarrollo)
# ===========================================================
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Muestra correos en consola
DEFAULT_FROM_EMAIL = 'Robotat <no-reply@uvg.edu.gt>'              # Dirección de remitente predeterminada

# Configuración SMTP real (para producción, actualmente comentada)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'tu-cuenta@uvg.edu.gt'
# EMAIL_HOST_PASSWORD = 'tu-password-o-app-password'


# ===========================================================
# Parámetros adicionales para restablecimiento de contraseña
# ===========================================================
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24                # Tiempo de validez del token de recuperación (24h)
FRONTEND_URL = "http://localhost:5173"               # URL base del frontend (para generar enlaces de reset)


# =================
# Django Channels 
# =================
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  # Comunicación asíncrona local en memoria
    },
}
